import { access, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const required=[
  'release/PRODUCT-SCOPE.v1.0.json','release/SCOPE-DEBT.v1.0.json','release/PUBLIC-CLAIMS.v1.0.json','release/CRITICAL-GATE-WAIVERS.v1.0.json',
  'release/EVIDENCE-ASSURANCE-POLICY.v1.0.json','release/EVIDENCE-REGISTRY.v1.0.json','release/EVIDENCE-NEGATIVE-RESULTS.v1.0.json','release/EVIDENCE-CORPUS-LOCK.v1.0.json','release/P18-EVIDENCE-ASSURANCE-EVIDENCE.v1.0.json',
  'release/SECURITY-REVIEW-POLICY.v1.0.json','release/SECURITY-THREAT-MODEL.v1.0.json','release/ASVS-5.0.0-CROSSCHECK.v1.0.json',
  'release/SECURITY-MALICIOUS-PACKAGE-CORPUS.v1.0.json','release/SECURITY-REGRESSION-REGISTRY.v1.0.json','release/SECURITY-RESIDUAL-RISKS.v1.0.json','release/SECURITY-STATIC-ANALYSIS-WAIVERS.v1.0.json','release/SECURITY-RESOURCE-DOS-REVIEW.v1.0.json','release/P12-PRODUCT-SECURITY-EVIDENCE.v1.0.json',
  'SECURITY.md','docs/production/PRODUCT-SECURITY-REVIEW.md','scripts/security-review-policy.mjs','scripts/security-dependency-audit.mjs','scripts/run-security-regressions.mjs','scripts/security-codeql-receipt.mjs','scripts/run-security-review.mjs',
  'tests/product-security.test.js','tests/security-hardening.test.js','tests/security-fuzz.test.js','tests/security-malicious-package.test.js','tests/p12-evidence.test.js',
  'release/OPERATIONS-POLICY.v1.0.json','release/KNOWN-ISSUES.v1.0.json','release/OPERATIONS-DISASTER-SCENARIOS.v1.0.json',
  'packages/operations/src/index.js','scripts/run-operations-drills.mjs','tests/operations-maintenance.test.js','docs/production/OPERATIONS-MAINTENANCE.md',
  'scripts/evidence-assurance-policy.mjs','scripts/evidence-assurance-bundle.mjs','scripts/build-evidence-assurance.mjs','scripts/capture-browser-evidence-assurance.mjs','scripts/verify-evidence-assurance.mjs','tests/evidence-assurance.test.js','tests/p18-evidence.test.js','docs/production/EVIDENCE-ASSURANCE.md',
  'scripts/verify-product-scope.mjs','scripts/verify-browser-profile.mjs','tests/product-scope.test.js','docs/production/PRODUCT-SCOPE-AND-CLAIMS.md',
  'tests/network-security.test.js','tests/p5-evidence.test.js','release/P5-NETWORK-PREVIEW-EVIDENCE.v1.0.json','docs/production/NETWORK-SECRET-PREVIEW-SECURITY.md',
  'packages/sdk/src/index.js','packages/kernel/src/index.js','packages/vfs/src/index.js','packages/process/src/index.js',
  'packages/process/src/sync-rpc.js',
  'tests/production-diagnostics.test.js','scripts/opencontainer-diagnostic.mjs','.github/ISSUE_TEMPLATE/opencontainer_bug.yml',
  'docs/production/DIAGNOSTICS-POLICY.v0.1.json','docs/production/DIAGNOSTICS-SUPPORT.md',
  'docs/api/PUBLIC-SDK.v0.1.json','docs/api/ERROR-CATALOG.v0.1.json','docs/api/API-REFERENCE.md','docs/api/ERROR-REFERENCE.md',
  'scripts/generate-developer-docs.mjs','tests/developer-docs.test.js','examples/sdk-failure-paths.mjs',
  'docs/guides/LIMITATIONS.md','docs/guides/SECURITY-MODEL.md','docs/guides/AI-CONSUMERS.md','docs/guides/MIGRATION.md','docs/guides/TROUBLESHOOTING.md',
  'docs/decisions/ADR-004-guest-capability-membrane.md','docs/decisions/ADR-005-service-worker-compatible-promotion.md','docs/decisions/ADR-006-release-storage-publication.md','docs/decisions/ADR-007-release-evidence-and-promotion.md',
  'release/CRITICAL-FLAKE-POLICY.v0.1.json','scripts/run-critical-flake-campaign.mjs','scripts/run-browser-flake-campaign.mjs',
  'packages/persistence/src/release-storage.js','tests/release-storage-migration.test.js',
  'release/RELEASE-POLICY.v0.1.json','release/RELEASE-CANDIDATE.v0.1.json','scripts/evaluate-release-preflight.mjs','tests/release-preflight.test.js',
  'release/HOTFIX-POLICY.v0.1.json','release/DEPRECATION-POLICY.v0.1.json','release/DEPRECATIONS.v0.1.json','scripts/verify-release-governance.mjs','tests/release-governance.test.js',
  'packages/protocol/src/service-worker-compatibility.js',
  'packages/package-env/src/index.js',
  'packages/package-env/src/browser-node-compat.js',
  'packages/package-env/src/resolver.js',
  'packages/package-env/src/native-esm-publication.js',
  'packages/package-env/src/commonjs-loader.js',
  'packages/package-env/src/frozen-install.js',
  'packages/package-env/src/command-bridge.js',
  'packages/package-env/src/builtins/path.js',
  'packages/package-env/src/builtins/events.js',
  'packages/package-env/src/builtins/registry.js',
  'packages/package-env/src/builtins/module.js',
  'packages/package-env/src/builtins/fs.js',
  'packages/package-env/src/builtins/process.js',
  'packages/package-env/src/builtins/url.js',
  'packages/package-env/src/builtins/buffer.js',
  'packages/package-env/src/virtual-node-modules.js','packages/network/src/index.js','packages/preview/src/index.js','packages/persistence/src/index.js',
  'packages/resources/src/index.js','packages/diagnostics/src/index.js','packages/protocol/src/index.js','packages/toolchain/src/index.js',
  'packages/toolchain/src/wasm-artifact-manager.js',
  'packages/toolchain/src/lightningcss-profile.js',
  'packages/toolchain/src/rolldown-browser-profile.js',
  'toolchain/artifacts/rolldown-wasi-1.2.9.json',
  'toolchain/artifacts/lightningcss-wasm-1.33.0.json',
  'toolchain/vendor/lightningcss-wasm-1.33.0.tgz',
  'toolchain/vendor/rolldown-browser-1.2.9.tgz',
  'toolchain/artifacts/rolldown-browser-1.2.9.json',
  'toolchain/artifacts/rolldown-runtime-deps-1.2.9.json',
  'toolchain/artifacts/vite-c1-runtime-8.3.0.json',
  'toolchain/artifacts/esm-lexer-3.0.2.json',
  'tests/runtime.test.js',
  'tests/resolver.test.js',
  'tests/node24-resolver-differential.test.js',
  'tests/commonjs-loader.test.js',
  'tests/frozen-install.test.js',
  'tests/node-core-builtins.test.js',
  'tests/runtime-builtins.test.js',
  'tests/package-command-bridge.test.js',
  'tests/wasm-artifact-manager.test.js',
  'tests/lightningcss-artifact.test.js',
  'tests/lightningcss-js-glue.test.js',
  'tests/rolldown-browser-artifact.test.js',
  'tests/rolldown-browser-execution.test.js',
  'tests/vite-c1-oracle.test.js',
  'tests/native-esm-publication.test.js',
  'tests/browser-esm-edge.test.js',
  'tests/browser-node-compat.test.js',
  'packages/process/src/browser-guest-worker.js','apps/playground/server.mjs'
];
for(const path of required)await access(resolve(path));
const root=JSON.parse(await readFile('package.json','utf8'));
if(root.engines?.node!=='24.21.0'||root.engines?.npm!=='11.19.0')throw new Error('Frozen Node/npm oracle changed');
const readme=await readFile('README.md','utf8');
if(!readme.includes('Not production-closed')&&!readme.includes('NOT production-closed'))throw new Error('README must retain production evidence boundary');
console.log('check: '+required.length+' required implementation artifacts present');
