import { access, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const required=[
  'release/PRODUCT-SCOPE.v1.0.json','release/SCOPE-DEBT.v1.0.json','release/PUBLIC-CLAIMS.v1.0.json','release/CRITICAL-GATE-WAIVERS.v1.0.json',
  'release/EVIDENCE-ASSURANCE-POLICY.v1.0.json','release/EVIDENCE-REGISTRY.v1.0.json','release/EVIDENCE-NEGATIVE-RESULTS.v1.0.json','release/EVIDENCE-CORPUS-LOCK.v1.0.json','release/P18-EVIDENCE-ASSURANCE-EVIDENCE.v1.0.json',
  'release/SECURITY-REVIEW-POLICY.v1.0.json','release/SECURITY-THREAT-MODEL.v1.0.json','release/ASVS-5.0.0-CROSSCHECK.v1.0.json',
  'release/SUPPLY-CHAIN-REVIEW-POLICY.v1.0.json','release/P13-SUPPLY-CHAIN-EVIDENCE.v1.0.json','scripts/run-supply-chain-review.mjs','tests/supply-chain-review.test.js','tests/p13-supply-chain-evidence.test.js','docs/production/SUPPLY-CHAIN-SECURITY-REVIEW.md','scripts/p13-openssf-scorecard.mjs','tests/p13-openssf-scorecard-source-audit.test.js','.github/workflows/scorecard.yml','docs/production/OPENSSF-HYGIENE.md','release/P13-OPENSSF-SCORECARD-EVIDENCE.v1.0.json','tests/p13-openssf-scorecard-evidence.test.js','scripts/build-historical-release-archive.mjs','scripts/verify-historical-release-archive.mjs','tests/p13-historical-archive-source-audit.test.js','docs/production/HISTORICAL-RELEASE-ARCHIVE.md','release/P13-HISTORICAL-ARCHIVE-EVIDENCE.v1.0.json','tests/p13-historical-archive-evidence.test.js','release/history/0.1.0-alpha.1/974fa1032c0d95c98889ca6f9bfaaa696c95fe9e/record.json',
  'release/RESOURCE-MEASUREMENT-POLICY.v1.0.json','release/P7-RESOURCE-WAVE1-EVIDENCE.v1.0.json','release/P7-RESOURCE-WAVE2-EVIDENCE.v1.0.json','scripts/capture-resource-evidence.mjs','scripts/audit-resource-retention.mjs','tests/resource-governance.test.js','tests/resource-retention-audit.test.js','tests/p7-resource-evidence.test.js','tests/p7-resource-wave2-evidence.test.js','docs/production/P7-RESOURCE-EVIDENCE.md','scripts/p7-declared-profile.mjs','apps/playground/public/p7-resource-profile.html','apps/playground/public/p7-resource-profile.js','apps/playground/public/p7-transfer-worker.mjs','tests/p7-wave3-source-audit.test.js','release/P7-RESOURCE-WAVE3-EVIDENCE.v1.0.json','tests/p7-wave3-evidence.test.js','scripts/p7-wave4.mjs','apps/playground/public/p7-resource-wave4.html','apps/playground/public/p7-resource-wave4.js','tests/p7-wave4-governor.test.js','tests/p7-wave4-source-audit.test.js','release/P7-RESOURCE-WAVE4-EVIDENCE.v1.0.json','tests/p7-wave4-evidence.test.js','scripts/install-current-stable-ci-chrome.sh','scripts/p14-browser-regression.mjs','tests/p14-browser-regression-source-audit.test.js','release/P14-BROWSER-REGRESSION-EVIDENCE.v1.0.json','tests/p14-browser-regression-evidence.test.js',
  'release/SECURITY-MALICIOUS-PACKAGE-CORPUS.v1.0.json','release/SECURITY-REGRESSION-REGISTRY.v1.0.json','release/SECURITY-RESIDUAL-RISKS.v1.0.json','release/SECURITY-STATIC-ANALYSIS-WAIVERS.v1.0.json','release/SECURITY-RESOURCE-DOS-REVIEW.v1.0.json','release/P12-PRODUCT-SECURITY-EVIDENCE.v1.0.json',
  'SECURITY.md','docs/production/PRODUCT-SECURITY-REVIEW.md','scripts/security-review-policy.mjs','scripts/security-dependency-audit.mjs','scripts/run-security-regressions.mjs','scripts/security-codeql-receipt.mjs','scripts/run-security-review.mjs',
  'tests/product-security.test.js','tests/security-hardening.test.js','tests/security-fuzz.test.js','tests/security-malicious-package.test.js','tests/p12-evidence.test.js',
  'release/OPERATIONS-POLICY.v1.0.json','release/KNOWN-ISSUES.v1.0.json','release/OPERATIONS-DISASTER-SCENARIOS.v1.0.json','release/P17-OPERATIONS-EVIDENCE.v1.0.json',
  'release/RELEASE-COMPATIBILITY-REPORT.v1.0.json','release/P11-RELEASE-COMPATIBILITY-EVIDENCE.v1.0.json','release/RELEASE-COMPATIBILITY-MATRIX.v1.0.json','release/P15-RELEASE-COMPATIBILITY-MATRIX-EVIDENCE.v1.0.json',
  'docs/compatibility/RELEASE-COMPATIBILITY-REPORT.md','docs/compatibility/RELEASE-COMPATIBILITY-MATRIX.md',
  'docs/compatibility/P4-PACKAGE-COMMAND-DIAGNOSTICS-NATIVE-BOUNDARY.md',
  'docs/compatibility/P2-RUNTIME-PROCESS-BOUNDARY.md',
  'docs/compatibility/P4-FINAL-PACKAGE-CLOSURE.md',
  'scripts/release-compatibility-report.mjs','scripts/release-compatibility-matrix.mjs',
  'tests/release-compatibility-report.test.js','tests/release-compatibility-matrix.test.js','tests/p11-release-report-evidence.test.js','tests/p15-compatibility-matrix-evidence.test.js','tests/p11-browser-floor-source-audit.test.js','release/P11-BROWSER-FLOOR-EVIDENCE.v1.0.json','tests/p11-browser-floor-evidence.test.js',
  'packages/operations/src/index.js','scripts/run-operations-drills.mjs','tests/operations-maintenance.test.js','tests/p17-evidence.test.js','docs/production/OPERATIONS-MAINTENANCE.md','.github/workflows/maintenance.yml',
  'scripts/evidence-assurance-policy.mjs','scripts/evidence-assurance-bundle.mjs','scripts/build-evidence-assurance.mjs','scripts/capture-browser-evidence-assurance.mjs','scripts/verify-evidence-assurance.mjs','tests/evidence-assurance.test.js','tests/p18-evidence.test.js','docs/production/EVIDENCE-ASSURANCE.md',
  'scripts/verify-product-scope.mjs','scripts/verify-browser-profile.mjs','tests/product-scope.test.js','docs/production/PRODUCT-SCOPE-AND-CLAIMS.md',
  'tests/network-security.test.js','tests/p5-evidence.test.js','release/P5-NETWORK-PREVIEW-EVIDENCE.v1.0.json','docs/production/NETWORK-SECRET-PREVIEW-SECURITY.md',
  'packages/sdk/src/index.js','packages/kernel/src/index.js','packages/vfs/src/index.js','packages/process/src/index.js',
  'packages/process/src/sync-rpc.js',
  'tests/production-diagnostics.test.js','scripts/opencontainer-diagnostic.mjs','.github/ISSUE_TEMPLATE/opencontainer_bug.yml',
  'docs/production/DIAGNOSTICS-POLICY.v0.1.json','docs/production/DIAGNOSTICS-SUPPORT.md',
  'docs/api/PUBLIC-SDK.v0.1.json','docs/api/ERROR-CATALOG.v0.1.json','docs/api/API-REFERENCE.md','docs/api/ERROR-REFERENCE.md',
  'scripts/generate-developer-docs.mjs','tests/developer-docs.test.js','examples/sdk-failure-paths.mjs',
  'docs/guides/LIMITATIONS.md','docs/guides/SECURITY-MODEL.md','docs/guides/AI-CONSUMERS.md','docs/guides/MIGRATION.md','docs/guides/TROUBLESHOOTING.md',
  'packages/ai-consumer/package.json','packages/ai-consumer/src/index.js','tests/p10-ai-consumer.test.js','tests/p10-ai-consumer-source-audit.test.js','tests/p10-ai-consumer-evidence.test.js','scripts/p10-ai-consumer-evidence.mjs','apps/playground/public/p10-ai-consumer.html','apps/playground/public/p10-ai-consumer.js','release/P10-AI-CONSUMER-EVIDENCE.v1.0.json',
  'docs/decisions/ADR-004-guest-capability-membrane.md','docs/decisions/ADR-005-service-worker-compatible-promotion.md','docs/decisions/ADR-006-release-storage-publication.md','docs/decisions/ADR-007-release-evidence-and-promotion.md',
  'release/CRITICAL-FLAKE-POLICY.v0.1.json','scripts/run-critical-flake-campaign.mjs','scripts/run-browser-flake-campaign.mjs',
  'packages/persistence/src/release-storage.js','tests/release-storage-migration.test.js','scripts/audit-p3-persistence-source.mjs','tests/p3-persistence-source-audit.test.js','release/P3-PERSISTENCE-WAVE1-EVIDENCE.v1.0.json','tests/p3-persistence-wave1-evidence.test.js','release/P3-PERSISTENCE-WAVE2-EVIDENCE.v1.0.json','scripts/capture-p3-wave2-browser-evidence.mjs','tests/p3-persistence-wave2-evidence.test.js','packages/persistence/src/corruption.js','packages/persistence/src/opfs-derived-index-store.js','tests/persistence-corruption.test.js','scripts/capture-p3-corruption-browser-evidence.mjs','release/P3-CORRUPTION-CLASSIFICATION-EVIDENCE.v1.0.json','tests/p3-corruption-evidence.test.js','packages/persistence/src/storage-cleanup.js','tests/storage-cleanup.test.js','scripts/capture-p3-low-storage-browser-evidence.mjs','release/P3-LOW-STORAGE-CLEANUP-EVIDENCE.v1.0.json','tests/p3-low-storage-evidence.test.js','scripts/capture-p3-safe-restore-browser-evidence.mjs','release/P3-SAFE-CHECKPOINT-RESTORE-EVIDENCE.v1.0.json','tests/p3-safe-restore-evidence.test.js','packages/vfs/src/workspace-lifecycle.js','tests/workspace-lifecycle.test.js','scripts/capture-p3-destructive-lifecycle-browser-evidence.mjs','release/P3-DESTRUCTIVE-LIFECYCLE-EVIDENCE.v1.0.json','tests/p3-destructive-lifecycle-evidence.test.js','packages/vfs/src/external-source.js','tests/external-source.test.js','scripts/capture-p3-external-source-browser-evidence.mjs','release/P3-EXTERNAL-SOURCE-MODES-EVIDENCE.v1.0.json','tests/p3-external-source-evidence.test.js','packages/vfs/src/opfs-sync-writer.js','packages/vfs/src/opfs-sync-writer-worker.js','tests/p3-durability-source-audit.test.js','scripts/capture-p3-durability-boundary-browser-evidence.mjs','release/P3-OPFS-DURABILITY-BOUNDARY-EVIDENCE.v1.0.json','tests/p3-durability-evidence.test.js','docs/production/P3-PERSISTENCE-EVIDENCE.md','docs/guides/STORAGE-AND-EXPORT.md',
  'release/RELEASE-POLICY.v0.1.json','release/RELEASE-CANDIDATE.v0.1.json','scripts/evaluate-release-preflight.mjs','tests/release-preflight.test.js',
  'release/HOTFIX-POLICY.v0.1.json','release/DEPRECATION-POLICY.v0.1.json','release/DEPRECATIONS.v0.1.json','scripts/verify-release-governance.mjs','tests/release-governance.test.js',
  'packages/protocol/src/service-worker-compatibility.js',
  'packages/package-env/src/index.js',
  'packages/package-env/src/browser-node-compat.js',
  'packages/package-env/src/resolver.js',
  'packages/package-env/src/native-esm-publication.js',
  'packages/package-env/src/commonjs-loader.js',
  'packages/package-env/src/frozen-install.js',
  'packages/package-env/src/command-bridge.js',
  'packages/package-env/src/builtins/path.js',
  'packages/package-env/src/builtins/events.js',
  'packages/package-env/src/builtins/registry.js',
  'packages/package-env/src/builtins/module.js',
  'packages/package-env/src/builtins/fs.js',
  'packages/package-env/src/builtins/process.js',
  'packages/package-env/src/builtins/url.js',
  'packages/package-env/src/builtins/buffer.js',
  'packages/package-env/src/virtual-node-modules.js','packages/network/src/index.js','packages/preview/src/index.js','packages/persistence/src/index.js',
  'packages/resources/src/index.js','packages/diagnostics/src/index.js','packages/protocol/src/index.js','packages/toolchain/src/index.js',
  'packages/toolchain/src/wasm-artifact-manager.js',
  'packages/toolchain/src/lightningcss-profile.js',
  'packages/toolchain/src/rolldown-browser-profile.js',
  'toolchain/artifacts/rolldown-wasi-1.2.9.json',
  'toolchain/artifacts/lightningcss-wasm-1.33.0.json',
  'toolchain/vendor/lightningcss-wasm-1.33.0.tgz',
  'toolchain/vendor/rolldown-browser-1.2.9.tgz',
  'toolchain/artifacts/rolldown-browser-1.2.9.json',
  'toolchain/artifacts/rolldown-runtime-deps-1.2.9.json',
  'toolchain/artifacts/vite-c1-runtime-8.3.0.json',
  'toolchain/artifacts/esm-lexer-3.0.2.json',
  'tests/runtime.test.js',
  'tests/resolver.test.js',
  'tests/node24-resolver-differential.test.js',
  'tests/commonjs-loader.test.js',
  'tests/frozen-install.test.js',
  'tests/node-core-builtins.test.js',
  'tests/runtime-builtins.test.js',
  'tests/package-command-bridge.test.js',
  'tests/wasm-artifact-manager.test.js',
  'tests/lightningcss-artifact.test.js',
  'tests/lightningcss-js-glue.test.js',
  'tests/rolldown-browser-artifact.test.js',
  'tests/rolldown-browser-execution.test.js',
  'tests/vite-c1-oracle.test.js',
  'tests/native-esm-publication.test.js',
  'tests/browser-esm-edge.test.js',
  'tests/browser-node-compat.test.js',
  'packages/process/src/browser-guest-worker.js','apps/playground/server.mjs',
  'scripts/p9-ui-rendered.mjs','tests/p9-ui-source-audit.test.js','release/P9-UI-RENDERED-EVIDENCE.v1.0.json','tests/p9-ui-evidence.test.js','scripts/install-frozen-ci-chrome.sh','docs/research/OPENCONTAINER-UX-STATE-FAILURE-MATRIX-v0.4-20260923.md','release/P9-FAILURE-SCENARIO-SOURCE.v1.0.json','scripts/p9-failure-matrix.mjs','packages/ui-contract/src/index.js','release/P9-FAILURE-COURT-MAP.v1.0.json','scripts/p9-failure-scenario-court.mjs','tests/p9-failure-scenario-corpus.test.js','release/P16-LEGAL-GOVERNANCE-POLICY.v1.0.json','release/P16-TEST-CORPUS-LICENSE-AUDIT.v1.0.json','release/P16-BCR-LICENSE-REVIEW.v1.0.json','release/P16-CLEAN-ROOM-SOURCE-REGISTER.v1.0.json','scripts/p16-legal-governance-readiness.mjs','tests/p16-legal-governance.test.js','CONTRIBUTING.md','CODE_OF_CONDUCT.md','GOVERNANCE.md','TRADEMARKS.md','docs/legal/CLEAN-ROOM-DESIGN-DIARY.md','docs/legal/AI-PROVIDER-DATA-EGRESS.md','docs/legal/JURISDICTION-ASSUMPTIONS.md','release/P9-FAILURE-SCENARIO-EVIDENCE.v1.0.json','tests/p9-failure-scenario-evidence.test.js','docs/production/P9-FAILURE-SCENARIOS.md'
];
for(const path of required)await access(resolve(path));
const root=JSON.parse(await readFile('package.json','utf8'));
if(root.engines?.node!=='24.21.0'||root.engines?.npm!=='11.19.0')throw new Error('Frozen Node/npm oracle changed');
const readme=await readFile('README.md','utf8');
if(!readme.includes('Not production-closed')&&!readme.includes('NOT production-closed'))throw new Error('README must retain production evidence boundary');
console.log('check: '+required.length+' required implementation artifacts present');
